apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  config.yml: |-
{{ .Values.cloud.config.yml | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: license
data:
  license.pem: |-
{{ .Values.cloud.license.pem | indent 4}}
