apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
data:
  config.yml: |-
{{ .Values.cloud.config.yml | indent 4}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: license
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
data:
  license.pem: |-
{{ .Values.cloud.license.pem | indent 4}}
