{{- if .Values.connect.enabled }}
{{- if not .Values.connect.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: connect-db-secret
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
    app: connect-db
type: Opaque
data:
  password: {{ required "connect.db.password is required when connect.externalSecrets.enabled=false" .Values.connect.db.password | b64enc | quote }}
  postgres-password: {{ required "connect.db.postgresPassword is required when connect.externalSecrets.enabled=false" .Values.connect.db.postgresPassword | b64enc | quote }}
{{- end }}
{{- end }}
