apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthy
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx
