{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: protopie-private-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
