{{- if .Values.imageCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: protopie-private-registry
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
