apiVersion: v1
kind: Service
metadata:
  name: ent-cloud-web-svc
  labels:
    {{- include "protopie.labels" . | nindent 4 }}
spec:
  selector:
    app: ent-cloud-web
  ports:
    - name: api
      port: 80
      targetPort: 3000
